- name: Configure systemd journald
  register: journald_config
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Journal]
      Storage=volatile
      Compress=4K
      Seal=no
      SplitMode=none
      RuntimeMaxUse=16M
      ForwardToSyslog=no
      ForwardToKMsg=no
      ForwardToConsole=no
      ForwardToWall=yes
      MaxLevelStore=notice
      MaxLevelWall=warning
      ReadKMsg=no
      Audit=no

- name: Apply systemd journald config
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  when: journald_config.changed

- name: Old Journald Folder does not exist
  ansible.builtin.file:
    path: /var/log/journal
    state: absent
