acl external-net { 192.168.1.0/24; };
acl internal-net { 192.168.0.0/24; 192.168.2.0/24; 192.168.3.0/24; 192.168.4.0/24; 192.168.5.0/24; 192.168.6.0/24; };
acl guest-net { 192.168.100.0/24; };

options {
  directory "/var/cache/bind";
  dnssec-validation auto;
  version "n/a";
  recursion yes;
  listen-on port 53 { 127.0.0.1; 192.168.0.2; 192.168.1.2; 192.168.2.2; 192.168.3.2; 192.168.4.2; 192.168.5.2; 192.168.6.2; 192.168.100.2; };
  allow-query { 127.0.0.0/8; external-net; internal-net; guest-net; };
  allow-recursion { 127.0.0.0/8; external-net; internal-net; guest-net; };
  allow-transfer { none; };
  forwarders {
    1.1.1.1;
    8.8.8.8;
  };
  querylog yes;
};

include "/etc/bind/rndc.key";
controls {
  inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { "rndc-key"; };
};

logging {
  category notify { zone_transfer_log; };
  category xfer-in { zone_transfer_log; };
  category xfer-out { zone_transfer_log; };
  channel zone_transfer_log {
    file "/var/named/log/transfer.log" versions 10 size 10m;
    print-time yes;
    print-category yes;
    print-severity yes;
    severity info;
  };
  category queries { query_log; };
  channel query_log {
    file "/var/named/log/query.log" versions 10 size 10m;
    print-time yes;
    print-category yes;
    print-severity yes;
    severity info;
  };
  category default { default_log; };
  category config { default_log; };
  category dispatch { default_log; };
  category network { default_log; };
  category general { default_log; };
  channel default_log {
    file "/var/named/log/default.log" versions 10 size 10m;
    print-time yes;
    print-category yes;
    print-severity yes;
    severity info;
  };
};

zone "." {
  type hint;
  file "/usr/share/dns/root.hints";
};


# management
zone "management.local." {
  type master;
  file "/etc/bind/zone.local.management";
};
zone "0.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.0";
};

# external
zone "external.local." {
  type master;
  file "/etc/bind/zone.local.external";
};
zone "1.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.1";
};

# main
zone "main.local." {
  type master;
  file "/etc/bind/zone.local.main";
};
zone "2.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.2";
};

# work
zone "work.local." {
  type master;
  file "/etc/bind/zone.local.work";
};
zone "3.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.3";
};

# media
zone "media.local." {
  type master;
  file "/etc/bind/zone.local.media";
};
zone "4.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.4";
};

# iot
zone "iot.local." {
  type master;
  file "/etc/bind/zone.local.iot";
};
zone "5.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.5";
};

# monitoring
zone "monitoring.local." {
  type master;
  file "/etc/bind/zone.local.monitoring";
};
zone "6.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.6";
};

# guest
zone "guest.local." {
  type master;
  file "/etc/bind/zone.local.guest";
};
zone "100.168.192.in-addr.arpa." {
  type master;
  file "/etc/bind/zone.arpa.in-addr.192.168.100";
};
